import type { Metadata } from "next";

import "./globals.css";
import Navbar from "./Navbar/page";
import Footer from "./Footer/page";

export const metadata: Metadata = {
  title: "JEWELLERY SHOP",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
